# Massive hack https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach
# I gave up on having a separate db container and just use the host's postgresql
# because I am in a rush.
version: '3'
services:
  app:
    build: .
    network_mode: "host" # hack
    ports:
      - "8000:8000" # is this even needed?
    environment:
      DB_HOST: 127.0.0.1 # hack
      DB_PORT: 5432

# version: '3'
# services:
#   app:
#     build: .
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       DB_HOST: db
#       DB_PORT: 5432
#       # DB_PORT: 5433
#   db:
#     image: postgres
#     environment:
#       POSTGRES_DB: asset_prices
#       POSTGRES_USER: sornette
#       POSTGRES_PASSWORD: sornette
#     # ports:
#     #   - "5433:5432"  # Maps to external address 5433
